spring:
  application:
    name: soda-service
  artemis:
    password: simetraehcapa
    user: artemis
  cache:
    jcache:
      config: classpath:ehcache.xml
  sql:
    init:
      mode: always
  datasource:
    username: application
    password: '123app*.'
    url: jdbc:postgresql://localhost:5432/sodaware
    hikari:
      maximum-pool-size: 7
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 1792
        useServerPrepStmts: true
  jpa:
    database: postgresql
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      hibernate:
        SQL: debug
    com:
      sodaware: debug
soda:
  inventory:
    service-host: http://localhost:8082

